#!/usr/bin/env bash
#
# VideoStream — one-shot, idempotent setup for a fresh Oracle Cloud
# Ampere A1 instance running Ubuntu 24.04 (arm64).
#
# Run it as a sudo-capable user (the default `ubuntu`), from this directory:
#
#     cd ~/videostream/deploy && ./oracle-setup.sh
#
# It is safe to re-run: every step checks before it changes anything. It will
# NOT overwrite an existing .env, and it always re-renders livekit.yaml and
# ingress.yaml from the templates + .env.
#
# What it does NOT do (you must, in the OCI console — see README.md):
#   * open the same ports in the VCN security list
#   * attach a reserved public IP
#   * upgrade the tenancy to pay-as-you-go
#   * point DNS at the instance
set -euo pipefail

cd "$(dirname "$0")"

# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------

if [[ $EUID -eq 0 ]]; then
	SUDO=""
else
	SUDO="sudo"
	command -v sudo >/dev/null || { echo "need root or sudo" >&2; exit 1; }
fi

log()  { printf '\n\033[1;36m==>\033[0m %s\n' "$*"; }
info() { printf '    %s\n' "$*"; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# Random strings. The subshell drops `pipefail` because `head -c` closing the
# pipe kills `tr` with SIGPIPE, which would otherwise abort the whole script.
rand_alnum()   { ( set +o pipefail; LC_ALL=C tr -dc 'A-Za-z0-9'    </dev/urandom | head -c "$1" ); }
rand_urlsafe() { ( set +o pipefail; LC_ALL=C tr -dc 'A-Za-z0-9_-' </dev/urandom | head -c "$1" ); }

[[ -f docker-compose.yml ]] || die "run this from the deploy/ directory"

# --------------------------------------------------------------------------
# 1. packages
# --------------------------------------------------------------------------

log "Updating apt and installing base packages"
export DEBIAN_FRONTEND=noninteractive
$SUDO apt-get update -qq
# gettext-base provides envsubst, used to render the yaml templates.
$SUDO apt-get install -y -qq ca-certificates curl gnupg gettext-base

# iptables-persistent asks two debconf questions on install; preseed them so an
# unattended run does not hang forever on a purple dialog.
log "Installing iptables-persistent / netfilter-persistent"
if dpkg -s iptables-persistent >/dev/null 2>&1; then
	info "already installed"
else
	echo 'iptables-persistent iptables-persistent/autosave_v4 boolean false' | $SUDO debconf-set-selections
	echo 'iptables-persistent iptables-persistent/autosave_v6 boolean false' | $SUDO debconf-set-selections
	$SUDO apt-get install -y -qq iptables-persistent
fi

log "Installing Docker Engine + compose plugin from Docker's apt repository"
if command -v docker >/dev/null 2>&1; then
	info "docker present: $(docker --version)"
	$SUDO docker compose version >/dev/null 2>&1 \
		|| $SUDO apt-get install -y -qq docker-compose-plugin
else
	$SUDO install -m 0755 -d /etc/apt/keyrings
	if [[ ! -f /etc/apt/keyrings/docker.asc ]]; then
		$SUDO curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
		$SUDO chmod a+r /etc/apt/keyrings/docker.asc
	fi
	# shellcheck disable=SC1091
	. /etc/os-release
	echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable" \
		| $SUDO tee /etc/apt/sources.list.d/docker.list >/dev/null
	$SUDO apt-get update -qq
	$SUDO apt-get install -y -qq docker-ce docker-ce-cli containerd.io \
		docker-buildx-plugin docker-compose-plugin
fi

$SUDO systemctl enable --now docker >/dev/null

# Convenience only; the group change needs a re-login, so this script keeps
# using sudo for docker below.
if [[ -n "$SUDO" ]] && ! id -nG "$USER" | tr ' ' '\n' | grep -qx docker; then
	log "Adding $USER to the docker group (log out and back in for it to apply)"
	$SUDO usermod -aG docker "$USER"
fi

# --------------------------------------------------------------------------
# 2. .env  (done before the firewall so the hairpin rule knows the public IP)
# --------------------------------------------------------------------------

if [[ -f .env ]]; then
	log ".env already exists — leaving it alone"
else
	log "Creating .env"
	[[ -t 0 ]] || die "no .env and no terminal to prompt on; copy .env.example to .env and fill it in"

	read -r -p "    Domain for the party (e.g. watch.example.com): " ASK_DOMAIN
	[[ -n "$ASK_DOMAIN" ]] || die "DOMAIN is required"

	DETECTED_IP="$(curl -fsS --max-time 10 https://ifconfig.me || true)"
	read -r -p "    Public IP [${DETECTED_IP:-none detected}]: " ASK_IP
	ASK_IP="${ASK_IP:-$DETECTED_IP}"
	[[ -n "$ASK_IP" ]] || die "PUBLIC_IP is required"

	OLD_UMASK="$(umask)"
	umask 077 # no world-readable window between creating and chmodding .env
	cat >.env <<-EOF
		# Generated by oracle-setup.sh on $(date -Is)
		# See .env.example for what each variable does.
		DOMAIN=${ASK_DOMAIN}
		PUBLIC_IP=${ASK_IP}
		LIVEKIT_API_KEY=API$(rand_alnum 12)
		LIVEKIT_API_SECRET=$(rand_urlsafe 32)
		SESSION_SECRET=$(rand_urlsafe 32)
	EOF
	umask "$OLD_UMASK"
	chmod 600 .env
	info "wrote .env (mode 600) with a freshly generated key pair"
fi

# Load it for the firewall rules, envsubst and the summary.
set -a
# shellcheck disable=SC1091
. ./.env
set +a
: "${DOMAIN:?DOMAIN missing from .env}"
: "${PUBLIC_IP:?PUBLIC_IP missing from .env}"
: "${LIVEKIT_API_KEY:?LIVEKIT_API_KEY missing from .env}"
: "${LIVEKIT_API_SECRET:?LIVEKIT_API_SECRET missing from .env}"

# --------------------------------------------------------------------------
# 3. instance firewall
#
# Oracle's Ubuntu image ships /etc/iptables/rules.v4 with, at the end of INPUT:
#     -A INPUT -j REJECT --reject-with icmp-host-prohibited
# Appending ACCEPT rules after it does nothing — they are never reached. Every
# rule below is therefore INSERTED at the REJECT rule's line number, which
# pushes the REJECT down and leaves our rule in front of it.
# --------------------------------------------------------------------------

reject_line() {
	# Line number of the first REJECT rule in INPUT, empty if there is none.
	$SUDO iptables -L INPUT --line-numbers -n | awk '$2 == "REJECT" { print $1; exit }'
}

allow() { # allow <tcp|udp> <port|first:last>
	local proto="$1" port="$2" line
	if $SUDO iptables -C INPUT -p "$proto" --dport "$port" -j ACCEPT 2>/dev/null; then
		info "$proto/$port already allowed"
		return
	fi
	line="$(reject_line)"
	if [[ -n "$line" ]]; then
		$SUDO iptables -I INPUT "$line" -p "$proto" --dport "$port" -j ACCEPT
		info "$proto/$port inserted at INPUT line $line (before REJECT)"
	else
		# No REJECT rule (someone already cleaned up the ruleset): append.
		$SUDO iptables -A INPUT -p "$proto" --dport "$port" -j ACCEPT
		info "$proto/$port appended to INPUT (no REJECT rule found)"
	fi
}

log "Opening ports in the instance firewall"
allow tcp 80           # HTTP: ACME challenges + redirect to HTTPS
allow tcp 443          # HTTPS: web app, LiveKit signalling (/rtc), Twirp
allow udp 443          # HTTP/3
allow tcp 7881         # LiveKit ICE/TCP fallback (for UDP-blocked clients)
allow udp 7882         # LiveKit WebRTC media (single UDP mux port)
allow tcp 5349         # TURN over TLS
allow udp 3478         # TURN over UDP
allow udp 30000:30100  # TURN relay allocation range
# Ingress profile (off by default): TCP 1935 (RTMP), UDP 7885 (WHIP media).
# allow tcp 1935
# allow udp 7885

# --------------------------------------------------------------------------
# 4. TURN hairpin
#
# A relay candidate points at the *public* IP. When livekit-server (or anything
# else on this box) tries to reach its own relay through that address, Oracle's
# 1:1 NAT does not hairpin the packet back in — it is simply dropped. This DNAT
# rewrites locally-originated traffic aimed at the public IP to the private NIC
# address, so relayed candidate pairs work.
# --------------------------------------------------------------------------

PRIVATE_IP="$(hostname -I | awk '{print $1}')"
[[ -n "$PRIVATE_IP" ]] || die "could not determine the private IP"

log "Adding the TURN hairpin DNAT ($PUBLIC_IP -> $PRIVATE_IP)"
if $SUDO iptables -t nat -C OUTPUT -d "$PUBLIC_IP" -j DNAT --to-destination "$PRIVATE_IP" 2>/dev/null; then
	info "already present"
else
	$SUDO iptables -t nat -A OUTPUT -d "$PUBLIC_IP" -j DNAT --to-destination "$PRIVATE_IP"
	info "added"
fi

log "Persisting iptables rules to /etc/iptables/rules.v4"
$SUDO netfilter-persistent save

# --------------------------------------------------------------------------
# 5. render the config templates
#
# envsubst is given an explicit variable list so anything else that looks like
# ${...} in the templates survives untouched.
# --------------------------------------------------------------------------

log "Rendering livekit.yaml and ingress.yaml"
envsubst '${DOMAIN} ${PUBLIC_IP} ${LIVEKIT_API_KEY} ${LIVEKIT_API_SECRET}' <livekit.yaml.tmpl >livekit.yaml
envsubst '${LIVEKIT_API_KEY} ${LIVEKIT_API_SECRET}' <ingress.yaml.tmpl >ingress.yaml
chmod 600 livekit.yaml ingress.yaml
info "wrote livekit.yaml and ingress.yaml (mode 600 — they contain the API secret)"

mkdir -p data # SQLite lives here, bind-mounted into the app container

# --------------------------------------------------------------------------
# 6. bring the stack up
# --------------------------------------------------------------------------

log "Pulling images (caddy, livekit)"
$SUDO docker compose pull caddy livekit

# The app image is built here from the checked-out source: the Dockerfile
# builds the SPA (node stage) and the Go binary that embeds it. First build on
# a 4-OCPU A1 takes a few minutes; later ones hit the layer cache.
log "Building the app image (this takes a few minutes the first time)"
$SUDO docker compose build app

log "Starting the stack"
$SUDO docker compose up -d
$SUDO docker compose ps

# --------------------------------------------------------------------------
# 7. what is left for you to do
# --------------------------------------------------------------------------

cat <<EOF

------------------------------------------------------------------------
  VideoStream should now be at:  https://${DOMAIN}
  LiveKit signalling:            wss://${DOMAIN}  (proxied by Caddy)
  API key:                       ${LIVEKIT_API_KEY}
  (the secret is in ./.env — never paste it anywhere else)

  Still to do, outside this machine:

  [ ] VCN security list — add the same ingress rules in the OCI console
      (Networking > Virtual Cloud Networks > your VCN > Subnet > Security
      List). iptables alone is not enough; Oracle drops the traffic before
      it ever reaches the instance:
        TCP  80, 443          0.0.0.0/0
        TCP  7881, 5349       0.0.0.0/0
        UDP  443, 7882, 3478  0.0.0.0/0
        UDP  30000-30100      0.0.0.0/0
        TCP  22               your IP only (tighten the default rule)
  [ ] Reserved public IP — an ephemeral one dies with the instance, and
      rtc.node_ip in livekit.yaml would then point at nothing.
  [ ] Upgrade the tenancy to pay-as-you-go. Still \$0 inside the Always Free
      limits, but it exempts you from idle reclamation (7 days under 20%
      CPU would otherwise delete an idle party server).
  [ ] DNS A records, both pointing at ${PUBLIC_IP}:
        ${DOMAIN}
        turn.${DOMAIN}
      Caddy cannot obtain certificates until these resolve.

  Then watch the certificates arrive:   sudo docker compose logs -f caddy
  And confirm TURN found its cert:      sudo docker compose logs livekit | grep -i turn
------------------------------------------------------------------------

EOF
