#!/usr/bin/env bash
#
# VideoStream — one-shot, idempotent setup for a fresh Oracle Cloud
# Ampere A1 instance running Ubuntu 24.04 (arm64).
#
# Run it as a sudo-capable user (the default `ubuntu`), from this directory:
#
#     cd ~/videostream/deploy && ./oracle-setup.sh
#
# It is safe to re-run: every step checks before it changes anything. It will
# NOT overwrite an existing .env, and it always re-renders livekit.yaml and
# ingress.yaml from the templates + .env.
#
# What it does NOT do (you must, in the OCI console — see README.md):
#   * open the same ports in the VCN security list (ufw here is not a
#     substitute: Oracle drops traffic before it reaches the instance)
#   * attach a reserved public IP
#   * upgrade the tenancy to pay-as-you-go
#   * point DNS at the instance
set -euo pipefail

cd "$(dirname "$0")"

# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------

if [[ $EUID -eq 0 ]]; then
	SUDO=""
else
	SUDO="sudo"
	command -v sudo >/dev/null || { echo "need root or sudo" >&2; exit 1; }
fi

log()  { printf '\n\033[1;36m==>\033[0m %s\n' "$*"; }
info() { printf '    %s\n' "$*"; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# Random strings. The subshell drops `pipefail` because `head -c` closing the
# pipe kills `tr` with SIGPIPE, which would otherwise abort the whole script.
rand_alnum()   { ( set +o pipefail; LC_ALL=C tr -dc 'A-Za-z0-9'    </dev/urandom | head -c "$1" ); }
rand_urlsafe() { ( set +o pipefail; LC_ALL=C tr -dc 'A-Za-z0-9_-' </dev/urandom | head -c "$1" ); }

[[ -f docker-compose.yml ]] || die "run this from the deploy/ directory"

# --------------------------------------------------------------------------
# 1. packages
# --------------------------------------------------------------------------

log "Updating apt and installing base packages"
export DEBIAN_FRONTEND=noninteractive
$SUDO apt-get update -qq
# gettext-base provides envsubst, used to render the yaml templates.
$SUDO apt-get install -y -qq ca-certificates curl gnupg gettext-base

log "Installing Docker Engine + compose plugin from Docker's apt repository"
if command -v docker >/dev/null 2>&1; then
	info "docker present: $(docker --version)"
	$SUDO docker compose version >/dev/null 2>&1 \
		|| $SUDO apt-get install -y -qq docker-compose-plugin
else
	$SUDO install -m 0755 -d /etc/apt/keyrings
	if [[ ! -f /etc/apt/keyrings/docker.asc ]]; then
		$SUDO curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
		$SUDO chmod a+r /etc/apt/keyrings/docker.asc
	fi
	# shellcheck disable=SC1091
	. /etc/os-release
	echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable" \
		| $SUDO tee /etc/apt/sources.list.d/docker.list >/dev/null
	$SUDO apt-get update -qq
	$SUDO apt-get install -y -qq docker-ce docker-ce-cli containerd.io \
		docker-buildx-plugin docker-compose-plugin
fi

$SUDO systemctl enable --now docker >/dev/null

# Convenience only; the group change needs a re-login, so this script keeps
# using sudo for docker below.
if [[ -n "$SUDO" ]] && ! id -nG "$USER" | tr ' ' '\n' | grep -qx docker; then
	log "Adding $USER to the docker group (log out and back in for it to apply)"
	$SUDO usermod -aG docker "$USER"
fi

# --------------------------------------------------------------------------
# 2. .env  (done before the firewall so the hairpin rule knows the public IP)
# --------------------------------------------------------------------------

if [[ -f .env ]]; then
	log ".env already exists — leaving it alone"
else
	log "Creating .env"
	[[ -t 0 ]] || die "no .env and no terminal to prompt on; copy .env.example to .env and fill it in"

	read -r -p "    Domain for the party (e.g. watch.example.com): " ASK_DOMAIN
	[[ -n "$ASK_DOMAIN" ]] || die "DOMAIN is required"

	DETECTED_IP="$(curl -fsS --max-time 10 https://ifconfig.me || true)"
	read -r -p "    Public IP [${DETECTED_IP:-none detected}]: " ASK_IP
	ASK_IP="${ASK_IP:-$DETECTED_IP}"
	[[ -n "$ASK_IP" ]] || die "PUBLIC_IP is required"

	OLD_UMASK="$(umask)"
	umask 077 # no world-readable window between creating and chmodding .env
	cat >.env <<-EOF
		# Generated by oracle-setup.sh on $(date -Is)
		# See .env.example for what each variable does.
		DOMAIN=${ASK_DOMAIN}
		PUBLIC_IP=${ASK_IP}
		LIVEKIT_API_KEY=API$(rand_alnum 12)
		LIVEKIT_API_SECRET=$(rand_urlsafe 32)
		SESSION_SECRET=$(rand_urlsafe 32)
	EOF
	umask "$OLD_UMASK"
	chmod 600 .env
	info "wrote .env (mode 600) with a freshly generated key pair"
fi

# Load it for the firewall rules, envsubst and the summary.
set -a
# shellcheck disable=SC1091
. ./.env
set +a
: "${DOMAIN:?DOMAIN missing from .env}"
: "${PUBLIC_IP:?PUBLIC_IP missing from .env}"
: "${LIVEKIT_API_KEY:?LIVEKIT_API_KEY missing from .env}"
: "${LIVEKIT_API_SECRET:?LIVEKIT_API_SECRET missing from .env}"

# --------------------------------------------------------------------------
# 3. instance firewall (ufw) + TURN hairpin
#
# ufw is the only thing standing between the internet and this box if the VCN
# security list is left permissive, so it is configured explicitly rather than
# left at whatever the image shipped.
#
# Two Docker-shaped caveats:
#
#   * Ports PUBLISHED by a container (caddy's 80/443) are DNAT'd in the nat
#     table and traverse FORWARD, not INPUT — ufw does not filter them, and a
#     `ufw deny 443` would not close them. They are listed below anyway so the
#     intent is readable, but Docker is what actually exposes them.
#
#   * livekit runs with network_mode: host, so ITS ports really do hit INPUT
#     and ufw governs them. That includes 7880, which caddy and app reach over
#     the bridge — allowed per-interface below so it stays private to the host.
#
# Oracle's image ships a REJECT-terminated INPUT chain plus iptables-persistent.
# Running both that and ufw means two things fighting over one ruleset, so the
# old chain is flushed and netfilter-persistent is disabled; ufw owns INPUT and
# restores itself at boot.
# --------------------------------------------------------------------------

log "Installing and configuring ufw"
$SUDO apt-get install -y -qq ufw

# SSH first and unconditionally: every later step is a chance to lock this box
# out, and Oracle's serial console is a miserable way to find that out.
$SUDO ufw allow 22/tcp comment 'SSH' >/dev/null

$SUDO ufw allow 80/tcp   comment 'HTTP: ACME + redirect'      >/dev/null
$SUDO ufw allow 443/tcp  comment 'HTTPS: app + livekit signal' >/dev/null
$SUDO ufw allow 443/udp  comment 'HTTP/3'                      >/dev/null
$SUDO ufw allow 7881/tcp comment 'LiveKit ICE/TCP fallback'    >/dev/null
$SUDO ufw allow 7882/udp comment 'LiveKit WebRTC media mux'    >/dev/null
$SUDO ufw allow 5349/tcp comment 'TURN over TLS'               >/dev/null
$SUDO ufw allow 3478/udp comment 'TURN over UDP'               >/dev/null
$SUDO ufw allow 30000:30100/udp comment 'TURN relay range'     >/dev/null
# Ingress profile (off by default):
# $SUDO ufw allow 1935/tcp comment 'RTMP ingress'
# $SUDO ufw allow 7885/udp comment 'WHIP ingress media'

# livekit's signalling/Twirp port: reachable from the container bridges only.
# Without this, caddy fails every /rtc and /twirp request with
# "dial tcp 172.17.0.1:7880: connect: no route to host" and no room can be
# created, while livekit itself looks perfectly healthy on *:7880.
# br-videostream is pinned in docker-compose.yml; docker0 is the default bridge.
for IFACE in docker0 br-videostream; do
	$SUDO ufw allow in on "$IFACE" to any port 7880 proto tcp \
		comment "livekit signalling from $IFACE" >/dev/null
done

# Docker manages its own FORWARD rules; ufw defaulting to DROP there breaks
# container networking in ways that look like random DNS failures.
if ! grep -q '^DEFAULT_FORWARD_POLICY="ACCEPT"' /etc/default/ufw; then
	$SUDO sed -i 's/^DEFAULT_FORWARD_POLICY=.*/DEFAULT_FORWARD_POLICY="ACCEPT"/' /etc/default/ufw
	info "set DEFAULT_FORWARD_POLICY=ACCEPT (Docker needs it)"
fi

# --------------------------------------------------------------------------
# TURN hairpin, as a nat block inside ufw's before.rules.
#
# A relay candidate points at the *public* IP. When livekit-server (or anything
# else on this box) tries to reach its own relay through that address, Oracle's
# 1:1 NAT does not hairpin the packet back in — it is simply dropped. This DNAT
# rewrites locally-originated traffic aimed at the public IP to the private NIC
# address, so relayed candidate pairs work.
#
# It lives in before.rules rather than in iptables-persistent so that ufw stays
# the single owner of the ruleset and it survives `ufw reload` and reboots.
# --------------------------------------------------------------------------

PRIVATE_IP="$(hostname -I | awk '{print $1}')"
[[ -n "$PRIVATE_IP" ]] || die "could not determine the private IP"

log "Installing the TURN hairpin DNAT ($PUBLIC_IP -> $PRIVATE_IP) into ufw"
BEFORE_RULES=/etc/ufw/before.rules
HAIRPIN_BEGIN="# BEGIN videostream TURN hairpin (managed by oracle-setup.sh)"
HAIRPIN_END="# END videostream TURN hairpin"

# Drop any previous block, then prepend a fresh one — so a changed PUBLIC_IP
# replaces the rule instead of stacking a second one.
$SUDO sed -i "/^${HAIRPIN_BEGIN}$/,/^${HAIRPIN_END}$/d" "$BEFORE_RULES"
$SUDO tee /tmp/hairpin.$$ >/dev/null <<-EOF
	${HAIRPIN_BEGIN}
	*nat
	:OUTPUT - [0:0]
	-A OUTPUT -d ${PUBLIC_IP} -j DNAT --to-destination ${PRIVATE_IP}
	COMMIT
	${HAIRPIN_END}
EOF
$SUDO sh -c "cat /tmp/hairpin.$$ '$BEFORE_RULES' > '$BEFORE_RULES.new' && mv '$BEFORE_RULES.new' '$BEFORE_RULES'"
$SUDO rm -f /tmp/hairpin.$$
info "hairpin DNAT written to $BEFORE_RULES"

# --------------------------------------------------------------------------
# Hand INPUT over to ufw.
# --------------------------------------------------------------------------

log "Enabling ufw"
if $SUDO ufw status | grep -q '^Status: active'; then
	$SUDO ufw --force reload >/dev/null
	info "ufw already active — reloaded"
else
	# Clear Oracle's stock REJECT-terminated chain and the old hairpin so the
	# two rulesets cannot both be live. The policy stays ACCEPT for the moment
	# between flush and enable, which is why SSH is allowed above first.
	$SUDO iptables -F INPUT
	$SUDO iptables -t nat -F OUTPUT 2>/dev/null || true
	$SUDO ufw --force enable >/dev/null
	info "ufw enabled"
fi

# iptables-persistent would restore the old rules on top of ufw's at boot.
if systemctl is-enabled netfilter-persistent >/dev/null 2>&1; then
	$SUDO systemctl disable netfilter-persistent >/dev/null 2>&1 || true
	info "disabled netfilter-persistent (ufw owns the ruleset now)"
fi

# Docker reinstalls its own chains on restart; do it after ufw rebuilt INPUT.
$SUDO systemctl restart docker
$SUDO ufw status verbose

# --------------------------------------------------------------------------
# 5. render the config templates
#
# envsubst is given an explicit variable list so anything else that looks like
# ${...} in the templates survives untouched.
# --------------------------------------------------------------------------

log "Rendering livekit.yaml and ingress.yaml"
envsubst '${DOMAIN} ${PUBLIC_IP} ${LIVEKIT_API_KEY} ${LIVEKIT_API_SECRET}' <livekit.yaml.tmpl >livekit.yaml
envsubst '${LIVEKIT_API_KEY} ${LIVEKIT_API_SECRET}' <ingress.yaml.tmpl >ingress.yaml
chmod 600 livekit.yaml ingress.yaml
info "wrote livekit.yaml and ingress.yaml (mode 600 — they contain the API secret)"

# SQLite lives here, bind-mounted into the app container. The runtime image is
# distroless:nonroot, so the server runs as uid 65532 and cannot write into a
# directory owned by the login user — without this chown the app crash-loops on
# "migrate: unable to open database file (14)".
mkdir -p data
$SUDO chown -R 65532:65532 data

# --------------------------------------------------------------------------
# 6. bring the stack up
# --------------------------------------------------------------------------

log "Pulling images (caddy, livekit)"
$SUDO docker compose pull caddy livekit

# The app image is built here from the checked-out source: the Dockerfile
# builds the SPA (node stage) and the Go binary that embeds it. First build on
# a 4-OCPU A1 takes a few minutes; later ones hit the layer cache.
log "Building the app image (this takes a few minutes the first time)"
$SUDO docker compose build app

log "Starting the stack"
$SUDO docker compose up -d
$SUDO docker compose ps

# --------------------------------------------------------------------------
# 7. what is left for you to do
# --------------------------------------------------------------------------

cat <<EOF

------------------------------------------------------------------------
  VideoStream should now be at:  https://${DOMAIN}
  LiveKit signalling:            wss://${DOMAIN}  (proxied by Caddy)
  API key:                       ${LIVEKIT_API_KEY}
  (the secret is in ./.env — never paste it anywhere else)

  Still to do, outside this machine:

  [ ] VCN security list — add the same ingress rules in the OCI console
      (Networking > Virtual Cloud Networks > your VCN > Subnet > Security
      List). ufw on this box is not enough; Oracle drops the traffic
      before it ever reaches the instance:
        TCP  80, 443          0.0.0.0/0
        TCP  7881, 5349       0.0.0.0/0
        UDP  443, 7882, 3478  0.0.0.0/0
        UDP  30000-30100      0.0.0.0/0
        TCP  22               your IP only (tighten the default rule)
  [ ] Reserved public IP — an ephemeral one dies with the instance, and
      rtc.node_ip in livekit.yaml would then point at nothing.
  [ ] Upgrade the tenancy to pay-as-you-go. Still \$0 inside the Always Free
      limits, but it exempts you from idle reclamation (7 days under 20%
      CPU would otherwise delete an idle party server).
  [ ] DNS A records, both pointing at ${PUBLIC_IP}:
        ${DOMAIN}
        turn.${DOMAIN}
      Caddy cannot obtain certificates until these resolve.

  Then watch the certificates arrive:   sudo docker compose logs -f caddy
  And confirm TURN found its cert:      sudo docker compose logs livekit | grep -i turn
------------------------------------------------------------------------

EOF
